import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Global controller for handling locale changes.
final ValueNotifier<Locale> appLocale = ValueNotifier(const Locale('vi'));

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      // Bottom Tabs
      'tabOverview': 'Tổng quan',
      'tabSolar': 'Điện mặt trời',
      'tabWincc': 'Thủy điện',
      'tabPerformance': 'Hiệu suất',
      'tabAlerts': 'Cảnh báo',

      // General SCADA status
      'winccOnline': 'WinCC Online',
      'signalLost': 'Mất tín hiệu',
      'operatingDiagram': 'SƠ ĐỒ VẬN HÀNH · CHỈ GIÁM SÁT',
      'dakrosa1DiagramTitle': 'Sơ đồ một sợi nhà máy Dakrosa 1',
      'dakrosa2DiagramTitle': 'Sơ đồ phân phối & tổ máy Dakrosa 2',
      'zoomHint': 'Dùng 2 ngón để phóng to sơ đồ',
      'fullscreenRotateTooltip': 'Xoay ngang màn hình',
      'close': 'Đóng',
      'dakrosa1FullscreenTitle': 'Dakrosa 1 · Sơ đồ một sợi',
      'dakrosa2FullscreenTitle': 'Dakrosa 2 · {0}',
      'scada22kvDiagram': 'Sơ đồ 22 kV',
      'turbineH': 'Tổ máy H{0}',

      // Dakrosa 1 Canvas / Telemetry
      'dakrosa1TelemetryHeader': 'Thông số vận hành của 3 tổ máy',
      'activePower': 'Công suất tác dụng',
      'reactivePower': 'Công suất phản kháng',
      'voltage': 'Điện áp',
      'current': 'Dòng điện',
      'frequency': 'Tần số',
      'powerFactor': 'Hệ số công suất',
      'speed': 'Tốc độ',
      'guideVane': 'Độ mở cánh hướng',
      'generatorWithNum': 'Tổ máy {0}',
      'hasSignal': 'CÓ TÍN HIỆU',
      'noSignal': 'MẤT TÍN HIỆU',
      'scadaDisclaimer': 'Giao diện chỉ hiển thị dữ liệu giám sát và không phát lệnh điều khiển tới hệ thống WinCC.',

      // Dakrosa 2 Canvas / Telemetry
      'readoutsWithDataHeader': '{0}/{1} thông số tổ máy đang có dữ liệu',
      'hasDataCount': '{0}/{1} THÔNG SỐ',
      'dakrosa2TelemetryFootnote': 'Dữ liệu không hợp lệ hoặc quá hạn được để trống.',
      'additionalStatusHeader': 'Tín hiệu trạng thái bổ sung · chỉ giám sát',
      'dakrosa2StatusFootnote': 'Tín hiệu chưa đủ dữ liệu được để trống.',

      // Dashboard header
      'mainTitleOverview': 'DAKROSA · Tổng quan',
      'mainSubtitleOverview': 'Cập nhật nhanh tình hình vận hành toàn hệ thống',
      'mainTitleSolar': 'Điện mặt trời Đăk Rosa',
      'mainSubtitleSolarDefault': 'Kon Tum, Việt Nam',
      'mainSubtitleSolarCommissioned': '{0} · Vận hành: {1}',
      'mainTitleWincc': 'Thủy điện WinCC',
      'mainTitlePerformance': 'Hiệu suất vận hành',
      'mainSubtitlePerformance': 'Sản lượng phát luỹ kế, bức xạ và giảm khí phát thải CO2',
      'mainTitleAlerts': 'Cảnh báo hệ thống',
      'mainSubtitleAlertsCount': 'Theo dõi độ trễ tín hiệu và cảnh báo thiết bị ({0} sự cố)',
      'allStations': 'Tất cả các trạm',
      'lastUpdated': 'Cập nhật:',
      'minutesAgo': '{0} phút trước',
      'justNow': 'vừa xong',

      // Overview
      'totalSystem': 'TỔNG HỆ THỐNG',
      'stationD1': 'THỦY ĐIỆN DAKROSA 1',
      'stationD2': 'THỦY ĐIỆN DAKROSA 2',
      'metricSolar': 'Công suất solar',
      'metricHydro': 'Công suất thủy điện',
      'metricTotal': 'Tổng công suất',
      'metricStationsOnline': 'Trạm thủy điện online',
      'cumulativeYield': 'Sản lượng phát điện lũy kế',
      'today': 'Hôm nay',
      'thisMonth': 'Tháng này',
      'thisYear': 'Năm nay',
      'detailsTitle': 'Xem chi tiết tổ máy',
      'detailsTitleClose': 'Thu gọn chi tiết tổ máy',
      'allPlants': 'Tất cả nhà máy',
      'solarLabel': 'Mặt trời',
      'solarSignalType': 'Tín hiệu nhà máy',
      'hydroSignalType': 'Tín hiệu thủy điện',
      'goodSignals': 'Tín hiệu tốt',
      'maxLatency': 'Trễ lớn nhất',
      'unitConnection': 'kết nối',
      'scadaSignalStatus': 'TRẠNG THÁI TÍN HIỆU SCADA',
      'solarPowerPlant': 'Nhà máy Điện mặt trời',
      'inverter': 'Inverter',
      'efficiency': 'Hiệu suất',
      'hydroPlantsCluster': 'Cụm nhà máy Thủy điện',
      'hydroPlantD1': 'Nhà máy Thủy điện Dakrosa 1',
      'hydroPlantD2': 'Nhà máy Thủy điện Dakrosa 2',
      'runningGenerators': 'Tổ máy chạy',
      'avgCosPhi': 'Cos φ TB',
      'hydroGeneratorsTitle': 'TỔ MÁY THỦY ĐIỆN {0}',
      'statusGenerating': 'Đang phát',
      'statusDisconnected': 'Mất kết nối',

      // Solar
      'solarTitle': 'Điện mặt trời',
      'yieldToday': 'Sản lượng hôm nay',
      'yieldMonth': 'Sản lượng tháng',
      'yieldYear': 'Sản lượng năm',
      'currentPerformance': 'Hiệu suất hiện tại',
      'solarRadiation': 'Bức xạ mặt trời',
      'pvTemperature': 'Nhiệt độ tấm pin',
      'ambientTemperature': 'Nhiệt độ môi trường',
      'yieldOverTime': 'Sản lượng theo thời gian',
      'day': 'Ngày',
      'week': 'Tuần',
      'month': 'Tháng',
      'year': 'Năm',
      'weatherSunny': 'Nắng',
      'radiationGhi': 'Bức xạ GHI',
      'panelTempLabel': 'Tấm pin: {0}°C',
      'inverterStatusLabel': 'Trạng thái Inverter',
      'allInvertersRunning': '100% đang hoạt động',
      'performancePrLabel': 'Hiệu suất PR',
      'totalYieldLabel': 'Tổng sản lượng',
      'currentCapacityLabel': 'CÔNG SUẤT HIỆN TẠI',
      'activeNowLabel': 'Hoạt động',
      'acEfficiency': 'Hiệu suất AC',
      'dcPower': 'Công suất DC',
      'dailyYield': 'Daily Yield', // or Daily Yield
      'periodDay': 'Ngày',
      'periodMonth': 'Tháng',
      'periodYear': 'Năm',
      'viewAll': 'Xem tất cả',
      'alertsMaintenance': 'Cảnh báo & Bảo trì',
      'highRadiationWarning': 'Cảnh báo bức xạ cao',
      'highRadiationWarningDetail': 'GHI hiện tại đạt 912 W/m²',
      'periodicCleaning': 'Vệ sinh tấm pin định kỳ',
      'periodicCleaningDetail': 'Khuyến nghị vệ sinh trong 5 ngày tới',
      'stableSystem': 'Hệ thống hoạt động ổn định',
      'stableSystemDetail': 'Không có lỗi phát sinh trong 24 giờ qua',

      // Performance
      'co2Offset': 'Giảm thiểu CO2',
      'treesPlanted': 'Tương đương {0} cây xanh',
      'totalGeneration': 'Tổng sản lượng phát',
      'totalSunnyHours': 'Tổng số giờ nắng',
      'totalRadiation': 'Tổng bức xạ tích lũy',
      'yieldMonthLabel': 'Sản lượng Tháng {0}',
      'yieldGoalMwh': 'Mục tiêu: {0} MWh',
      'yieldYearLabel': 'Sản lượng Năm {0}',
      'sinceCommissioning': 'Từ khi vận hành',
      'systemCapacity': 'Công suất hệ thống',
      'gridConnectedCapacity': '5.00 MWac (Hòa lưới)',
      'carbonOffset': 'Carbon Offset',
      'treesPlantedEquivalent': 'Tương đương ~{0} nghìn cây xanh',
      'compositePerformance': 'HIỆU SUẤT TỔNG HỢP',
      'ghiIrradianceEquiv': 'Bức xạ quy đổi GHI',
      'estimatedFromPower': 'Ước tính từ công suất phát',
      'dailyPrEfficiency': 'Hiệu suất ngày PR',
      'monthlyYield': 'Sản lượng Tháng',
      'yearlyYield': 'Sản lượng Năm',

      // Alerts
      'signalLatency': 'Theo dõi độ trễ tín hiệu',
      'latency': 'Trễ kết nối',
      'hours': 'giờ',
      'noAlerts': 'Không có cảnh báo',
      'systemHealthy': 'Hệ thống hoạt động bình thường, không ghi nhận sự cố.',
      'incidentLogTitle': 'NHẬT KÝ SỰ CỐ & CẢNH BÁO',
      'signalInterruptedTitle': 'Tín hiệu bị gián đoạn',
      'signalInterruptedBody': 'Một số nguồn dữ liệu Scada phản hồi chậm hoặc lỗi mạng.',
      'checkInverterNoGeneration': 'Kiểm tra inverter không phát',
      'inverterNoGenerationBody': '{0}/{1} inverter chưa có sản lượng hôm nay',
      'highTempAlertTitle': 'Trạm {0} Tổ máy {1} nhiệt độ cao',
      'highTempAlertBody': 'Nhiệt độ lớn nhất {0}°C (vượt ngưỡng an toàn)',
      'noAlertsDetail': 'Không phát hiện sự cố kết nối hoặc nhiệt độ bất thường.',
      'alertTimeLabel': 'Thời gian: {0}',
      'yesterday': 'Hôm qua',

      // Hydro Tab Specifics
      'giamsatthuydien': 'Giám sát thủy điện Dakrosa',
      'stationCount': '{0} trạm',
      'scadaOnlineDiagram': 'Sơ đồ SCADA trực tuyến - {0}',
      'statusRunning': 'Đang chạy',
      'statusStopped': 'Dừng máy',
      'lblCurrent': 'DÒNG',
      'lblVoltage': 'ĐIỆN ÁP',
      'lblFrequency': 'TẦN SỐ',
      'lblFactor': 'HỆ SỐ',
      'lblSpeed': 'TỐC ĐỘ',
      'lblGuideVane': 'CÁNH HƯỚNG',
      'lblTemp': 'NHIỆT ĐỘ',
      'lblToday': 'HÔM NAY',
      'updatedSecondsAgoPlaceholder': 'Cập nhật -- giây trước',
      'updatedSecondsAgo': 'Cập nhật {0} giây trước',
      'updatedMinutesSecondsAgo': 'Cập nhật {0} phút {1} giây trước',
      'updatedMinutesAgo': 'Cập nhật {0} phút trước',
      'updatedHoursAgo': 'Cập nhật {0} giờ trước',
      'signalOk': 'Có tín hiệu',
      'statusReceiving': 'Đang nhận',
      'statusDelayed': 'Trễ',
      'statusExceeded': 'Quá ngưỡng',
      'statusUnknown': 'Không rõ',
      'lblU': 'U: {0} kV',
      'lblFactorShort': 'Hệ số công suất: {0}',
      'lblF': 'F: {0} Hz',
      'lblTodayShort': 'Hôm nay: {0} MWh',
      'detailIndexTable': 'Bảng chỉ số chi tiết',
      'indexCount': '{0} chỉ số',
      'metricUnitsRunning': 'Tổ máy đang chạy',
      'metricInvertersRunning': 'Inverter đang chạy',
      'dataAge': 'Tuổi dữ liệu',
      'activePowerP': 'Công suất P',
      'reactivePowerQ': 'Công suất Q',
      'apparentPowerS': 'Công suất S',
      'busVoltage': 'Điện áp thanh cái',
      'busCurrent': 'Dòng thanh cái',
      'cosPhiFactor': 'Hệ số cos phi',
      'yield5Min': 'Sản lượng 5 phút',
      'unitPowerP': 'Tổ {0} - Công suất P',
      'unitPowerQ': 'Tổ {0} - Công suất Q',
      'unitCurrent': 'Tổ {0} - Dòng điện',
      'unitVoltage': 'Tổ {0} - Điện áp',
      'unitSpeed': 'Tổ {0} - Tốc độ',
      'unitCosPhi': 'Tổ {0} - Hệ số cos phi',
      'unitShort': 'Tổ {0}',
      'genBusP': 'Công suất bus máy phát',
      'genBusQ': 'Phản kháng bus máy phát',
      'genBusS': 'Biểu kiến bus máy phát',
      'genBusU12': 'Điện áp bus máy phát UAB',
      'genBusU23': 'Điện áp bus máy phát UBC',
      'genBusU31': 'Điện áp bus máy phát UCA',
      'genBusI1': 'Dòng bus máy phát pha A',
      'genBusI2': 'Dòng bus máy phát pha B',
      'genBusI3': 'Dòng bus máy phát pha C',
      'genBusIAvg': 'Dòng TB bus máy phát',
      'genBusUAvg': 'Điện áp TB bus máy phát',
      'genBusU1N': 'Điện áp bus máy phát A-N',
      'genBusF': 'Tần số bus máy phát',
      'genBusPF': 'Hệ số bus máy phát',
      'connectingSystem': 'Đang kết nối hệ thống...',
      'syncingData': 'Đang đồng bộ dữ liệu SCADA & Solar Cloud',
      'connectionFailed': 'Không thể kết nối',
      'checkNetwork': 'Vui lòng kiểm tra lại kết nối mạng của thiết bị.',
      'retry': 'Thử lại',
      'statusRunningEst': 'Đang chạy · Ước tính',
      'statusStoppedEst': 'Dừng · Ước tính',
      'statusUndefined': 'Chưa xác định',
      'derivedQualifier': ' (Ước tính)',
    },
    'en': {
      // Bottom Tabs
      'tabOverview': 'Overview',
      'tabSolar': 'Solar',
      'tabWincc': 'WinCC',
      'tabPerformance': 'Performance',
      'tabAlerts': 'Alerts',

      // General SCADA status
      'winccOnline': 'WinCC Online',
      'signalLost': 'Signal Lost',
      'operatingDiagram': 'OPERATING DIAGRAM · MONITORING ONLY',
      'dakrosa1DiagramTitle': 'Single Line Diagram of Dakrosa 1 Plant',
      'dakrosa2DiagramTitle': 'Distribution & Generator Diagram of Dakrosa 2',
      'zoomHint': 'Pinch with 2 fingers to zoom diagram',
      'fullscreenRotateTooltip': 'Rotate landscape',
      'close': 'Close',
      'dakrosa1FullscreenTitle': 'Dakrosa 1 · Single Line Diagram',
      'dakrosa2FullscreenTitle': 'Dakrosa 2 · {0}',
      'scada22kvDiagram': '22 kV Diagram',
      'turbineH': 'Generator H{0}',

      // Dakrosa 1 Canvas / Telemetry
      'dakrosa1TelemetryHeader': 'Operational telemetry of 3 generators',
      'activePower': 'Active Power',
      'reactivePower': 'Reactive Power',
      'voltage': 'Voltage',
      'current': 'Current',
      'frequency': 'Frequency',
      'powerFactor': 'Power Factor',
      'speed': 'Speed',
      'guideVane': 'Guide Vane Opening',
      'generatorWithNum': 'Generator {0}',
      'hasSignal': 'ONLINE',
      'noSignal': 'OFFLINE',
      'scadaDisclaimer': 'The interface only displays monitoring data and does not issue control commands to the WinCC system.',

      // Dakrosa 2 Canvas / Telemetry
      'readoutsWithDataHeader': '{0}/{1} turbine telemetry parameters have data',
      'hasDataCount': '{0}/{1} PARAMS',
      'dakrosa2TelemetryFootnote': 'Invalid or stale data are left blank.',
      'additionalStatusHeader': 'Additional status signals · monitoring only',
      'dakrosa2StatusFootnote': 'Signals with insufficient data are left blank.',

      // Dashboard header
      'mainTitleOverview': 'DAKROSA · Overview',
      'mainSubtitleOverview': 'Quick updates on system-wide operations',
      'mainTitleSolar': 'Dak Rosa Solar',
      'mainSubtitleSolarDefault': 'Kon Tum, Vietnam',
      'mainSubtitleSolarCommissioned': '{0} · Commissioned: {1}',
      'mainTitleWincc': 'WinCC Hydro',
      'mainTitlePerformance': 'Operational Performance',
      'mainSubtitlePerformance': 'Cumulative yield, solar radiation and CO2 offset',
      'mainTitleAlerts': 'System Alerts',
      'mainSubtitleAlertsCount': 'Monitor signal latency and alerts ({0} issues)',
      'allStations': 'All Stations',
      'lastUpdated': 'Updated:',
      'minutesAgo': '{0} min ago',
      'justNow': 'just now',

      // Overview
      'totalSystem': 'TOTAL SYSTEM',
      'stationD1': 'DAKROSA 1 HYDRO',
      'stationD2': 'DAKROSA 2 HYDRO',
      'metricSolar': 'Solar power',
      'metricHydro': 'Hydro power',
      'metricTotal': 'Total power',
      'metricStationsOnline': 'Hydro stations online',
      'cumulativeYield': 'Cumulative Energy Generation',
      'today': 'Today',
      'thisMonth': 'This month',
      'thisYear': 'This year',
      'detailsTitle': 'Show generator details',
      'detailsTitleClose': 'Hide generator details',
      'allPlants': 'All plants',
      'solarLabel': 'Solar',
      'solarSignalType': 'Solar signals',
      'hydroSignalType': 'Hydro signals',
      'goodSignals': 'Good signals',
      'maxLatency': 'Max Latency',
      'unitConnection': 'connection',
      'scadaSignalStatus': 'SCADA SIGNAL STATUS',
      'solarPowerPlant': 'Solar Power Plant',
      'inverter': 'Inverter',
      'efficiency': 'Efficiency',
      'hydroPlantsCluster': 'Hydro Power Plants',
      'hydroPlantD1': 'Dakrosa 1 Hydro Plant',
      'hydroPlantD2': 'Dakrosa 2 Hydro Plant',
      'runningGenerators': 'Running generators',
      'avgCosPhi': 'Average Cos φ',
      'hydroGeneratorsTitle': 'HYDRO GENERATORS {0}',
      'statusGenerating': 'Generating',
      'statusDisconnected': 'Disconnected',

      // Solar
      'solarTitle': 'Solar Power',
      'yieldToday': 'Yield today',
      'yieldMonth': 'Yield this month',
      'yieldYear': 'Yield this year',
      'currentPerformance': 'Current Performance',
      'solarRadiation': 'Solar Radiation',
      'pvTemperature': 'PV Temperature',
      'ambientTemperature': 'Ambient Temperature',
      'yieldOverTime': 'Energy yield over time',
      'day': 'Day',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'weatherSunny': 'Sunny',
      'radiationGhi': 'Radiation GHI',
      'panelTempLabel': 'PV Panel: {0}°C',
      'inverterStatusLabel': 'Inverter Status',
      'allInvertersRunning': '100% operational',
      'performancePrLabel': 'PR Performance',
      'totalYieldLabel': 'Total Yield',
      'currentCapacityLabel': 'CURRENT CAPACITY',
      'activeNowLabel': 'Active Now',
      'acEfficiency': 'AC Efficiency',
      'dcPower': 'DC Power',
      'dailyYield': 'Daily Yield',
      'periodDay': 'Day',
      'periodMonth': 'Month',
      'periodYear': 'Year',
      'viewAll': 'View all',
      'alertsMaintenance': 'Alerts & Maintenance',
      'highRadiationWarning': 'High Radiation Warning',
      'highRadiationWarningDetail': 'Current GHI reaches 912 W/m²',
      'periodicCleaning': 'Periodic panel cleaning',
      'periodicCleaningDetail': 'Recommended cleaning in the next 5 days',
      'stableSystem': 'System operates stably',
      'stableSystemDetail': 'No errors in the past 24 hours',

      // Performance
      'co2Offset': 'CO2 Offset',
      'treesPlanted': 'Equivalent to {0} trees',
      'totalGeneration': 'Total Energy Generated',
      'totalSunnyHours': 'Total Sunshine Hours',
      'totalRadiation': 'Total Solar Radiation',
      'yieldMonthLabel': 'Yield Month {0}',
      'yieldGoalMwh': 'Goal: {0} MWh',
      'yieldYearLabel': 'Yield Year {0}',
      'sinceCommissioning': 'Since commissioning',
      'systemCapacity': 'System Capacity',
      'gridConnectedCapacity': '5.00 MWac (Grid-tied)',
      'carbonOffset': 'Carbon Offset',
      'treesPlantedEquivalent': 'Equivalent to ~{0}k trees planted',
      'compositePerformance': 'COMPOSITE PERFORMANCE',
      'ghiIrradianceEquiv': 'GHI Irradiance Equivalent',
      'estimatedFromPower': 'Estimated from power output',
      'dailyPrEfficiency': 'Daily PR Efficiency',
      'monthlyYield': 'Monthly Yield',
      'yearlyYield': 'Yearly Yield',

      // Alerts
      'signalLatency': 'Signal Latency Monitor',
      'latency': 'Connection latency',
      'hours': 'hrs',
      'noAlerts': 'No active alerts',
      'systemHealthy': 'System is healthy, no warnings found.',
      'incidentLogTitle': 'INCIDENT LOG & ALERTS',
      'signalInterruptedTitle': 'Signal Interrupted',
      'signalInterruptedBody': 'Some SCADA data sources are responding slowly or network error.',
      'checkInverterNoGeneration': 'Check non-generating inverter',
      'inverterNoGenerationBody': '{0}/{1} inverters have no generation today',
      'highTempAlertTitle': 'Station {0} Unit {1} high temp',
      'highTempAlertBody': 'Max temperature {0}°C (exceeds safety threshold)',
      'noAlertsDetail': 'No connection issues or abnormal temperatures detected.',
      'alertTimeLabel': 'Time: {0}',
      'yesterday': 'Yesterday',

      // Hydro Tab Specifics
      'giamsatthuydien': 'Dakrosa Hydro Monitoring',
      'stationCount': '{0} stations',
      'scadaOnlineDiagram': 'Online SCADA Diagram - {0}',
      'statusRunning': 'Running',
      'statusStopped': 'Stopped',
      'lblCurrent': 'CURRENT',
      'lblVoltage': 'VOLTAGE',
      'lblFrequency': 'FREQUENCY',
      'lblFactor': 'FACTOR',
      'lblSpeed': 'SPEED',
      'lblGuideVane': 'GUIDE VANE',
      'lblTemp': 'TEMPERATURE',
      'lblToday': 'TODAY',
      'updatedSecondsAgoPlaceholder': 'Updated -- seconds ago',
      'updatedSecondsAgo': 'Updated {0} seconds ago',
      'updatedMinutesSecondsAgo': 'Updated {0} min {1} sec ago',
      'updatedMinutesAgo': 'Updated {0} minutes ago',
      'updatedHoursAgo': 'Updated {0} hours ago',
      'signalOk': 'Connected',
      'statusReceiving': 'Receiving',
      'statusDelayed': 'Delayed',
      'statusExceeded': 'Exceeded',
      'statusUnknown': 'Unknown',
      'lblU': 'U: {0} kV',
      'lblFactorShort': 'Power Factor: {0}',
      'lblF': 'F: {0} Hz',
      'lblTodayShort': 'Today: {0} MWh',
      'detailIndexTable': 'Detailed Index Table',
      'indexCount': '{0} indices',
      'metricUnitsRunning': 'Running generators',
      'metricInvertersRunning': 'Running inverters',
      'dataAge': 'Data Age',
      'activePowerP': 'Active Power P',
      'reactivePowerQ': 'Reactive Power Q',
      'apparentPowerS': 'Apparent Power S',
      'busVoltage': 'Bus Voltage',
      'busCurrent': 'Bus Current',
      'cosPhiFactor': 'Power Factor cos φ',
      'yield5Min': '5-Min Yield',
      'unitPowerP': 'Unit {0} - Active Power P',
      'unitPowerQ': 'Unit {0} - Reactive Power Q',
      'unitCurrent': 'Unit {0} - Current',
      'unitVoltage': 'Unit {0} - Voltage',
      'unitSpeed': 'Unit {0} - Speed',
      'unitCosPhi': 'Unit {0} - Power Factor',
      'unitShort': 'Unit {0}',
      'genBusP': 'Gen Bus Active Power',
      'genBusQ': 'Gen Bus Reactive Power',
      'genBusS': 'Gen Bus Apparent Power',
      'genBusU12': 'Gen Bus Voltage UAB',
      'genBusU23': 'Gen Bus Voltage UBC',
      'genBusU31': 'Gen Bus Voltage UCA',
      'genBusI1': 'Gen Bus Current Phase A',
      'genBusI2': 'Gen Bus Current Phase B',
      'genBusI3': 'Gen Bus Current Phase C',
      'genBusIAvg': 'Gen Bus Average Current',
      'genBusUAvg': 'Gen Bus Average Voltage',
      'genBusU1N': 'Gen Bus Voltage A-N',
      'genBusF': 'Gen Bus Frequency',
      'genBusPF': 'Gen Bus Power Factor',
      'connectingSystem': 'Connecting to system...',
      'syncingData': 'Syncing SCADA & Solar Cloud data',
      'connectionFailed': 'Connection failed',
      'checkNetwork': 'Please check your device\'s network connection.',
      'retry': 'Retry',
      'statusRunningEst': 'Running · Est.',
      'statusStoppedEst': 'Stopped · Est.',
      'statusUndefined': 'Undefined',
      'derivedQualifier': ' (Est.)',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String translateWithArgs(String key, List<dynamic> args) {
    String value = translate(key);
    for (int i = 0; i < args.length; i++) {
      value = value.replaceAll('{$i}', args[i].toString());
    }
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['vi', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizedString on BuildContext {
  String tr(String key) => AppLocalizations.of(this).translate(key);
  String trArgs(String key, List<dynamic> args) => AppLocalizations.of(this).translateWithArgs(key, args);
}
